name: Build with Tests

env:
  CONFIGURATION: Release
  RUN_TESTS: true

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v3
      with:
       dotnet-version: | 
         8.0.x
              
    - name: Build Project
      run: |
        dotnet build ./ActExample/ActExample.csproj -c CONFIGURATION

    - name: Run Tests
      if: env.RUN_TESTS == 'true'
      run: |
        dotnet test ./ActExampleTests/ActExampleTests.csproj -c CONFIGURATION
